# This file was generated by GoReleaser. DO NOT EDIT.
cask "nssh" do
  version "2.5.1"

  on_macos do
    on_intel do
      sha256 "00032da6c8c2ad3db9303f638dbca30f602916be609a215e3c030d85d7e2bab2"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f56992b86d0b4662f640204e8b3d9d950b6c66909e4ab13810cc121cdf5611b6"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c9f323eb2e9d3c190fc5191581993e74622fcbd401e124ab20c3696e98e84937"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a34a4e1476821adffc51cfb2bb0c8bd2655dc883bd4ec1e6d35aa3198233a81"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nssh"
  desc "Paste images into Claude Code over SSH"
  homepage "https://github.com/abizer/nssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nssh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nssh"] if OS.mac?
  end

  zap trash: [
      "~/.config/nssh",
      "~/.local/state/nssh",
    ]

end
