# This file was generated by GoReleaser. DO NOT EDIT.
cask "nssh" do
  version "2.5.0"

  on_macos do
    on_intel do
      sha256 "dbfc32010ee68d2376861a3cd71a5f17756cfd8b648fcf4b67e6631c215edf83"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ccb447adf4795a57a065cc42e681e02cffeb1318c3c7ea26b8c56537c45e5a4b"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a14da664a9b885a30e8f92e6cb08d7b8e1bccf79d4972cfc32a33bfbd5da6f60"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1873c74cac9714c5c2e7d55bda62abb5dac5e28558a120caeb5d45dea95e96a1"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nssh"
  desc "Paste images into Claude Code over SSH"
  homepage "https://github.com/abizer/nssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nssh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nssh"] if OS.mac?
  end

  zap trash: [
      "~/.config/nssh",
      "~/.local/state/nssh",
    ]

end
