# This file was generated by GoReleaser. DO NOT EDIT.
cask "nssh" do
  version "2.4.1"

  on_macos do
    on_intel do
      sha256 "0c1d5a98e227f65c6d7467cbcb49d3cd999c7fc49f243135b73cda3eb6d66dfe"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "14c9d11b621c91dace16417da6effaa09771d0365c50eb375f54cb46f4729fb5"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fff9c0253ca33dd1b00b18d567d3fe0f2b03df3eb0e974adc12c83498be54a5c"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "87b23dca50ac3acc8d36c5ed8a126dcbcb6e0b6e34f0fcdb4e8cc1d9a17aeee3"
      url "https://github.com/abizer/nssh/releases/download/v#{version}/nssh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nssh"
  desc "Paste images into Claude Code over SSH"
  homepage "https://github.com/abizer/nssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nssh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nssh"]
    end
  end

  # No zap stanza required

end
