# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nssh < Formula
  desc "Paste images into Claude Code over SSH"
  homepage "https://github.com/abizer/nssh"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abizer/nssh/releases/download/v2.4.0/nssh_2.4.0_darwin_amd64.tar.gz"
      sha256 "865d920fe4e578dfdb450bd5a1711f7663eb9f59ed63c28f5ad988c773bbf04c"

      define_method(:install) do
        bin.install "nssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abizer/nssh/releases/download/v2.4.0/nssh_2.4.0_darwin_arm64.tar.gz"
      sha256 "d9b88a533245cb52f3ae91e35c088c3520d6f81a22db33e416c83189d976a3e1"

      define_method(:install) do
        bin.install "nssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abizer/nssh/releases/download/v2.4.0/nssh_2.4.0_linux_amd64.tar.gz"
      sha256 "9f3bcaeb39243d0190afc890aac9208926dcb1183c2fee632a4c1ee92f166e3b"
      define_method(:install) do
        bin.install "nssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abizer/nssh/releases/download/v2.4.0/nssh_2.4.0_linux_arm64.tar.gz"
      sha256 "dd9a7d8c7e762c4ca930898223ca4df91df2451f3997883ec255c330aac88544"
      define_method(:install) do
        bin.install "nssh"
      end
    end
  end

  test do
    assert_match "usage: nssh", shell_output("#{bin}/nssh 2>&1", 1)
  end
end
