# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nssh < Formula
  desc "Paste images into Claude Code over SSH"
  homepage "https://github.com/abizer/nssh"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abizer/nssh/releases/download/v2.1.0/nssh_2.1.0_darwin_amd64.tar.gz"
      sha256 "56904042b51b935510ba71bb363b21da24de17adf3644a5f2c6184cebe5160ae"

      define_method(:install) do
        bin.install "nssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abizer/nssh/releases/download/v2.1.0/nssh_2.1.0_darwin_arm64.tar.gz"
      sha256 "75d09c63d509e8c66767c940c34b24f86d8458b1d396044f44f4d95c342891a1"

      define_method(:install) do
        bin.install "nssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abizer/nssh/releases/download/v2.1.0/nssh_2.1.0_linux_amd64.tar.gz"
      sha256 "bc3d30dec6087d667d0b01f11dfeef0fb56e12787f22c3362ac579cbeae8098c"
      define_method(:install) do
        bin.install "nssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abizer/nssh/releases/download/v2.1.0/nssh_2.1.0_linux_arm64.tar.gz"
      sha256 "5849647ed447650a15733936d8989c5e6dcf541ab6e984b13268a5a70d554491"
      define_method(:install) do
        bin.install "nssh"
      end
    end
  end

  test do
    assert_match "usage: nssh", shell_output("#{bin}/nssh 2>&1", 1)
  end
end
