# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nssh < Formula
  desc "Paste images into Claude Code over SSH"
  homepage "https://github.com/abizer/nssh"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abizer/nssh/releases/download/v2.3.0/nssh_2.3.0_darwin_amd64.tar.gz"
      sha256 "c0d8496ebd1ac090871c5d23cd195766f624eddc128b9d08659f825cca159864"

      define_method(:install) do
        bin.install "nssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abizer/nssh/releases/download/v2.3.0/nssh_2.3.0_darwin_arm64.tar.gz"
      sha256 "8dbb2561283e93013d18090c078fdd9386ef6bb0173db263b227623191ad5951"

      define_method(:install) do
        bin.install "nssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abizer/nssh/releases/download/v2.3.0/nssh_2.3.0_linux_amd64.tar.gz"
      sha256 "6379af1756558a1e4f9f1581fdf3501589e5794774c12a297b523c6481a20935"
      define_method(:install) do
        bin.install "nssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abizer/nssh/releases/download/v2.3.0/nssh_2.3.0_linux_arm64.tar.gz"
      sha256 "94fccc9c692040e7d355c93df32e0c30902a102a4aef2830128bd3581bec0532"
      define_method(:install) do
        bin.install "nssh"
      end
    end
  end

  test do
    assert_match "usage: nssh", shell_output("#{bin}/nssh 2>&1", 1)
  end
end
